Update jenkins-pipeline-java-demo

diff --git a/jenkins-pipeline-java-demo b/jenkins-pipeline-java-demo
--- a/jenkins-pipeline-java-demo
+++ b/jenkins-pipeline-java-demo
@@ -4,7 +4,10 @@ pipeline {
         stage('build') {
             steps {
                  echo 'Building java code'
-                 echo 'Welcome to the world of Jenkins pipeline with Java'
+                 sh '''javac jenkins.java
+                 java jenkins
+                 '''
+                 //echo 'Fail!';exit 1
             }
         }
          stage('test') {
